# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '85837b34-63db-4c1d-89b4-57def530aeb5'
  imageRepository: 'bluecollardevmediashare'
  containerRegistry: 'mediashare.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Pay-As-You-Go(49762f68-bfa4-48cd-8b3c-2d3ebe4735d5)'
          azureContainerRegistry: '{"loginServer":"mediashare.azurecr.io", "id" : "/subscriptions/49762f68-bfa4-48cd-8b3c-2d3ebe4735d5/resourceGroups/mediashare/providers/Microsoft.ContainerRegistry/registries/mediashare"}'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'up'
          arguments: '-p --build -V -d' 
