version: '3.8'
services:
  media-api-dev:
    image: 'node:14-slim'
    container_name: docker-nest-js
    build:
      context: .
      dockerfile: Dockerfile.slim
    user: 'node'
    working_dir: /usr/src/app
    environment:
      - APP_HOST={DOCKER_HOST}
      - NODE_ENV=production
      - APP_NAME=MediaApi
      - APP_PORT=3333
      - APP_PREFIX=api
      - APP_TITLE=Mediashare
      - DB_HOST=db
      - DB_URL=mongodb://db:27017/
      - SESSION_DB_NAME=api-session
      - SESSION_SECRET=this-is-my-secret-key
      - SESSION_DB_COLLECTION=session
      - MS_PORT=4000
      - DB_TYPE=mongodb
      - DB=mediashare
      - DB_SSL=false
      - DB_SYNCHRONIZE=true
      - DB_USERNAME=mongodb
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - '3333:3333'
    tty: true
    command: 'npm start'
    depends_on:
      - db
    networks:
      - mediashare
    links:
      - 'db:database'

  media-auth-dev:
    image: 'node:14-slim'
    container_name: media-auth
    build:
      context: .
      dockerfile: Dockerfile.slim
    user: 'node'
    working_dir: /usr/src/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRESS_PORT=5432
      - POSTGRES_USERNAME=ms-user
      - POSTGRES_PASSWORD=ms-user-pass
      - POSTGRES_DB=ms-user
      - NODE_ENV=production
      - SESSION_SECRET=this-is-my-secret-key
      - MS_PORT=4000
      - MS_HOST={DOCKER_HOST}
      - MS_API_PORT=4444
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - '4444:4444'
      - '4000:4000'
    tty: true
    command: 'nx serve media-auth --watch'
    networks:
      - mediashare
    depends_on:
      - mediapostgres
    links:
      - 'mediapostgres:postgres'

  mediapostgres:
    image: postgres
    container_name: media-postgres
    restart: always
    environment:
      - POSTGRES_USER=ms-user
      - POSTGRES_PASSWORD=ms-user-pass
      - POSTGRES_DB=ms-user
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5432:5432'
      - '443:443'
      - '80:80'
    volumes:
      - ms-postgres-data:/var/lib/postgres/data
    networks:
      - mediashare

  db:
    image: mongo:4.0.4
    container_name: media-mongo
    environment:
      - MONGODB_DATABASE='mediashare'
    volumes:
      - ms-mongo-data:/var/lib/mongodb/data
    ports:
      - '27017:27017'
    networks:
      - mediashare

networks:
  mediashare:

volumes:
  ms-mongo-data:
  ms-postgres-data:
  node-cache:
