version: '3.8'
services:
  media-api:
    container_name: MediaApi
    image: alpine:3.12
    ports:
      - 3333:3333
    environment:
      - APP_HOST=localhost
      - NODE_ENV=
      - APP_NAME=
      - APP_PORT=3333
      - APP_PREFIX=api
      - APP_TITLE=Mediashare
      - DB_URL=mongodb://localhost:27017/
      - SESSION_DB=
      - SESSION_SECRET=
      - SESSION_DB_COLLECTION=
      - MS_AUTH_PORT=
      - DB_TYPE=
      - DB=
      - DB_SSL=
      - DB_SYNCHRONIZE=
      - DB_USERNAME=
      - DB_PASSWORD=
      - MS_AUTH_PORT=

    volumes:
      - .:/src

  db-postgres:
    image: postgres
    container_name: ms-user
    restart: always
    environment:
      - POSTGRES_USER=ms-user
      - POSTGRES_PASSWORD=ms-user-pass
      - POSTGRES_DB=ms-user
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5432:5432
      - 443:443
      - 80:80
    volumes:
      - ms-postgres-data/var/lib/postgres/data

  db-mongo:
    image: mongo:4.0.4
    container_name: api-mongo
    environment:
      - MONGODB_DATABASE='mediashare'
    volumes:
      - ms-mongo-data:/var/lib/mongodb/data
    ports:
      - 27017:27017

networks:
  mediashare:

volumes:
  ms-mongo-data:
  ms-postgres-data:
