version: '3'
services:
  db-postgres:
    image: postgres
    container_name: ms-user
    restart: always
    environment:
      - POSTGRES_USER=ms-user
      - POSTGRES_PASSWORD=ms-user-pass
      - POSTGRES_DB=ms-user
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5432:5432
      - 443:443
      - 80:80
    volumes:
      - ms-postgres-data/var/lib/postgres/data

  db-mongo:
    image: mongo:4.0.4
    container_name: api-mongo
    environment:
      - MONGODB_DATABASE='mediashare'
    volumes:
      - ms-mongo-data:/var/lib/mongodb/data
    ports:
      - 27017:27017

volumes:
  ms-mongo-data:
  ms-postgres-data:
